name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
     
      - name: Publish Extensions Nuget Package
        id: publish_nuget_extensions
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/CardboardBox.Extensions/CardboardBox.Extensions.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
     
      - name: Publish AspNetCore Extensions Nuget Package
        id: publish_nuget_extensions_aspnetcore
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/CardboardBox.Extensions.AspNetCore/CardboardBox.Extensions.AspNetCore.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
     
      - name: Publish Excel Extensions Nuget Package
        id: publish_nuget_extensions_aspnetcore
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/CardboardBox.Extensions.Excel/CardboardBox.Extensions.Excel.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
     
      - name: Publish Scripting Extensions Nuget Package
        id: publish_nuget_extensions_scripting
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/CardboardBox.Extensions.Scripting/CardboardBox.Extensions.Scripting.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}